# Generated by Django 3.2 on 2022-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220916_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/types/icons/'),
        ),
        migrations.AlterField(
            model_name='profiletype',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
