# Generated by Django 3.2 on 2022-09-22 18:54

from django.db import migrations, models
import django.db.models.deletion
import utils.fields
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
        ('energy_saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_price', models.FloatField()),
                ('price_after_rise', models.IntegerField()),
                ('rise_level', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.models.CheckAgeMixin),
        ),
        migrations.CreateModel(
            name='GroupIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='groups/icons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalisationIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='localisations/icons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='rooms/icons/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='device',
            old_name='devices_types',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='month',
            old_name='consumption',
            new_name='avg_active_time',
        ),
        migrations.AddField(
            model_name='day',
            name='active_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='energy_saving.month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='energy_class',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='energy_saving.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='localisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='energy_saving.room'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_localisations', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('date', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('date', 'device')},
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('consumption', models.IntegerField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='energy_saving.devicetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('description', utils.fields.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/images/')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='energy_saving.groupicon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='day',
            name='consumption',
        ),
        migrations.AddField(
            model_name='device',
            name='active_days',
            field=models.ManyToManyField(related_name='devices', to='energy_saving.WeekDay'),
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='energy_saving.group'),
        ),
        migrations.AddField(
            model_name='localisation',
            name='energy_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localisations', to='energy_saving.energyprice'),
        ),
        migrations.AddField(
            model_name='localisation',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localisations', to='energy_saving.localisationicon'),
        ),
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rooms', to='energy_saving.roomicon'),
        ),
    ]
