version: "3.9"
services:
  web:
    platform: linux/amd64
    build: .
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
    - db
    - redis
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: db/Dockerfile
    image: postgres:latest
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - "6379:6379"